"""Add is_active from profile to user table

Revision ID: 443e477eed94
Revises: c05051291ddc
Create Date: 2023-04-07 11:54:18.408865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443e477eed94'
down_revision = 'c05051291ddc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'is_active')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.add_column('profiles', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
